# =======================================
# = Server Configuration
# =======================================
server:
  port: 22503


# =======================================
# = Spring Configuration
# =======================================
spring:
  application:
    name: test-service
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:database
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect


# =======================================
# = Eureka Configuration
# =======================================
eureka:
  client:
    service-url:
      defaultZone: http://localhost:22500/eureka
  instance:
    prefer-ip-address: true
